version: '3.8'

services:
  app_portfolio_track_api:
    build: .
    container_name: app_portfolio_track_api
    restart: unless-stopped
    env_file:
    - .env
    networks:
      awl_network:
        aliases:
        - portfolio-track-api
networks:
  awl_network:
    external: true
